name: Build Check

on:
  pull_request:
    branches:
      - master
      - '**'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      # Step 2: Setup Node.js and Install Dependencies
      - name: Setup Node.js and Install PNPM
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'
          cache: 'pnpm'
      
      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: pnpm install

      # Step 5: Build the Next.js Application
      - name: Build Next.js Application
        run: pnpm build

      # Step 6: Verify Build is Successful
      - name: Verify Build
        run: |
          if [ ! -d ".next" ]; then
            echo "Build failed. .next directory not found."
            exit 1
          else
            echo "Build was successful."
          fi
