name: Lint and Validate Checks

on:
  pull_request:
    branches:
      - master
      - '**'

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Prettier Check
        run: pnpm prettier:check

      - name: Run Lint Check
        run: pnpm lint

      - name: Validate Types
        run: pnpm validate-types

      - name: Run Stylelint
        run: pnpm stylelint
